---
- name: ensure jail is created
  iocage:
    zpool: zroot
    name: test
    state: present
    release: 12.0-RELEASE
  register: create

- debug:
    var: create

- name: Ensure jail is started
  iocage:
    name: test
    release: 12.0-RELEASE
    state: started
    properties:
      boot: "on"
  register: start

- debug:
    var: start

- name: Ensure jail is stopped
  iocage:
    name: test
    release: 12.0-RELEASE
    state: present
  register: stop

- debug:
    var: stop

- name: Ensure jail is stopped
  iocage:
    name: test
    release: 12.0-RELEASE
    state: absent
  register: destroy

- debug:
    var: destroy

#- name: Ensure wrong state is recognized
#  iocage:
#    name: test
#    release: 12.0-RELEASE
#    state: wrong
#  register: wrongstate
#
#- debug:
#    var: wrong_state
